config/routes.rb
Rails.application.routes.draw do
  resources :exercises
  resources :workouts
  resources :members
  root 'members#index', as: :authenticated_root
  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exercise.rb
class Exercise < ApplicationRecord
  belongs_to :workout
end

app/models/member.rb
class Member < ApplicationRecord
  has_many :workouts
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable, :registerable, :recoverable
  devise :database_authenticatable, :rememberable, :trackable, :validatable
end

app/models/workout.rb
class Workout < ApplicationRecord
  belongs_to :member
  has_many :exercises

  accepts_nested_attributes_for :exercises, allow_destroy: true, reject_if: :all_blank
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/exercises_controller.rb
class ExercisesController < AdminController
  before_action :set_exercise, only: [:show, :edit, :update, :destroy]

  # GET /exercises
  # GET /exercises.json
  def index
    @search_string = "name_cont"
    @q = Exercise.ransack(params[:q])
    @exercises = @q.result(distinct: true).order("updated_at DESC").page(params[:page]).per(50)
  end

  # GET /exercises/1
  # GET /exercises/1.json
  def show
  end

  # GET /exercises/new
  def new
    @exercise = Exercise.new
  end

  # GET /exercises/1/edit
  def edit
  end

  # POST /exercises
  # POST /exercises.json
  def create
    @exercise = Exercise.new(exercise_params)

    respond_to do |format|
      if @exercise.save
        format.html { redirect_to exercises_path, notice: 'Exercise was successfully created.' }
        format.json { render :index, status: :created, location: @exercise }
      else
        format.html { render :new }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exercises/1
  # PATCH/PUT /exercises/1.json
  def update
    respond_to do |format|
      if @exercise.update(exercise_params)
        format.html { redirect_to exercises_path, notice: 'Exercise was successfully updated.' }
        format.json { render :index, status: :ok, location: @exercise }
      else
        format.html { render :edit }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exercises/1
  # DELETE /exercises/1.json
  def destroy
    @exercise.destroy
    respond_to do |format|
      format.html { redirect_to exercises_url, notice: 'Exercise was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exercise
      @exercise = Exercise.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exercise_params
      params.require(:exercise).permit(:name, :total_set, :weights, :duration, :comments, :workout_id)
    end
end

app/controllers/members_controller.rb
class MembersController < AdminController
  before_action :set_member, only: [:show, :edit, :update, :destroy]

  # GET /members
  # GET /members.json
  def index
    @search_string = "first_name_or_last_name_cont"
    @q = Member.ransack(params[:q])
    @members = @q.result(distinct: true).order(:last_name).page(params[:page]).per(50)
  end

  # GET /members/1
  # GET /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to members_path, notice: 'Member was successfully created.' }
        format.json { render :index, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to members_path, notice: 'Member was successfully updated.' }
        format.json { render :index, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:first_name, :last_name, :height)
    end
end

app/controllers/workouts_controller.rb
class WorkoutsController < AdminController
  before_action :set_workout, only: [:show, :edit, :update, :destroy]

  # GET /workouts
  # GET /workouts.json
  def index
    @search_string = "workout_date_eq"
    @q = Workout.ransack(params[:q])
    @workouts = @q.result(distinct: true).order(:workout_date).page(params[:page]).per(50)
  end

  # GET /workouts/1
  # GET /workouts/1.json
  def show
  end

  # GET /workouts/new
  def new
    @workout = Workout.new
  end

  # GET /workouts/1/edit
  def edit
  end

  # POST /workouts
  # POST /workouts.json
  def create
    @workout = Workout.new(workout_params)

    respond_to do |format|
      if @workout.save
        format.html { redirect_to workouts_path, notice: 'Workout was successfully created.' }
        format.json { render :index, status: :created, location: @workout }
      else
        format.html { render :new }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workouts/1
  # PATCH/PUT /workouts/1.json
  def update
    respond_to do |format|
      if @workout.update(workout_params)
        format.html { redirect_to workouts_path, notice: 'Workout was successfully updated.' }
        format.json { render :index, status: :ok, location: @workout }
      else
        format.html { render :edit }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workouts/1
  # DELETE /workouts/1.json
  def destroy
    @workout.destroy
    respond_to do |format|
      format.html { redirect_to workouts_url, notice: 'Workout was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workout
      @workout = Workout.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def workout_params
      params.require(:workout).permit(:workout_date, :member_id, :comments, :weight,
                                      :bone_density, :bmi, :body_fat, :muscle_mass, :water,
                                      exercises_attributes: [:_destroy, :name,
                                                             :total_set, :weights, :duration, :comments]
      )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/exercises/_form.html.erb
<%= form_with(model: exercise, local: true) do |form| %>
  <% if exercise.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(exercise.errors.count, "error") %> prohibited this exercise from being saved:</h2>

      <ul>
      <% exercise.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row form-group">
    <div class="col-sm">
      <%= form.label :name %>
      <%= form.text_field :name, class: "form-control" %>
    </div>

    <div class="col-sm">
      <%= form.label :total_set %>
      <%= form.number_field :total_set, class: "form-control" %>
    </div>

    <div class="col-sm">
      <%= form.label :weights %>
      <%= form.text_field :weights, class: "form-control" %>
    </div>

    <div class="col-sm">
      <%= form.label :duration %>
      <%= form.number_field :duration, class: "form-control" %>
    </div>

    <div class="col-sm">
      <%= form.label :workout_id %>
      <%= form.number_field :workout_id, class: "form-control" %>
    </div>
  </div>

  <div class="row form-group">
    <div class="col-sm">
      <%= form.label :comments %>
      <%= form.text_area :comments, class: "form-control" %>
    </div>
  </div>

  <br />

  <div class="actions">
    <%= form.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/exercises/edit.html.erb
<h1>Editing Exercise</h1>

<%= render 'form', exercise: @exercise %>

app/views/exercises/index.html.erb
<% if notice %>
  <div class="alert alert-success" role="alert">
    <%= notice %>
  </div>
<% end %>

<h1>Exercises</h1>
<%= render "layouts/search" %>
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Total set</th>
      <th>Weights</th>
      <th>Duration</th>
      <th>Comments</th>
      <th>Workout</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @exercises.each do |exercise| %>
      <tr>
        <td><%= exercise.name %></td>
        <td><%= exercise.total_set %></td>
        <td><%= exercise.weights %></td>
        <td><%= exercise.duration %></td>
        <td><%= exercise.comments %></td>
        <td><%= exercise.workout_id %></td>
        <td><%= link_to 'Show', exercise %></td>
        <td><%= link_to 'Edit', edit_exercise_path(exercise) %></td>
        <td><%= link_to 'Destroy', exercise, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Exercise', new_exercise_path, class: "btn btn-primary" %>

app/views/exercises/new.html.erb
<h1>New Exercise</h1>

<%= render 'form', exercise: @exercise %>

app/views/exercises/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @exercise.name %>
</p>

<p>
  <strong>Total set:</strong>
  <%= @exercise.total_set %>
</p>

<p>
  <strong>Weights:</strong>
  <%= @exercise.weights %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @exercise.duration %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @exercise.comments %>
</p>

<p>
  <strong>Workout:</strong>
  <%= @exercise.workout_id %>
</p>

<%= link_to 'Edit', edit_exercise_path(@exercise) %> |
<%= link_to 'Back', exercises_path %>

app/views/layouts/_search.html.erb
<%= search_form_for @q do |f| %>
  <div class="row float-right mr-1" style="max-width: 400px">
    <%= f.search_field @search_string.to_sym, value: params[:q].try(:values).try(:first), placeholder: "Search", class: "form-control col-sm mr-3" %>
    <%= f.submit "Search", class: "btn btn-primary col-sm", style: "max-width: 100px" %>
  </div>
<% end %>
<br />
<br />
<br />

app/views/layouts/_sidenav.html.erb
<div id="accordion">

  <div class="card">
    <div class="card-header" style="padding: 0; margin: 0" id="headingMembers">
      <button class="btn btn-link" data-toggle="collapse" data-target="#collapseMembers" aria-expanded="true" aria-controls="collapseMembers">
        Members
      </button>
    </div>
    <div id="collapseMembers" class="collapse <%= controller.controller_name == 'members' ? 'show' : '' %>" aria-labelledby="headingMembers" data-parent="#accordion">
      <div class="card-body">
        <%= link_to 'Members', members_path %><br />
        <%= link_to 'New member', new_member_path %>
      </div>
    </div>
  </div>


  <div class="card">
    <div class="card-header" style="padding: 0; margin: 0" id="headingWorkouts">
      <button class="btn btn-link" data-toggle="collapse" data-target="#collapseWorkouts" aria-expanded="true" aria-controls="collapseWorkouts">
        Workouts
      </button>
    </div>
    <div id="collapseWorkouts" class="collapse <%= controller.controller_name == 'workouts' ? 'show' : '' %>" aria-labelledby="headingWorkouts" data-parent="#accordion">
      <div class="card-body">
        <%= link_to 'Workouts', workouts_path %><br />
        <%= link_to 'New workout', new_workout_path %>
      </div>
    </div>
  </div>


  <div class="card">
    <div class="card-header" style="padding: 0; margin: 0" id="headingExercises">
      <button class="btn btn-link" data-toggle="collapse" data-target="#collapseExercises" aria-expanded="true" aria-controls="collapseExercises">
        Exercises
      </button>
    </div>
    <div id="collapseExercises" class="collapse <%= controller.controller_name == 'exercises' ? 'show' : '' %>" aria-labelledby="headingExercises" data-parent="#accordion">
      <div class="card-body">
        <%= link_to 'Exercises', exercises_path %><br />
        <%= link_to 'New exercise', new_exercise_path %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_topnav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Workout</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <!--       <li class="nav-item active">
              <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Features</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Pricing</a>
            </li> -->
    </ul>
    <span class="navbar-text">
      <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
    </span>
  </div>
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workouts</title>
  <%= csrf_meta_tags %>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <%= stylesheet_link_tag    'admin', media: 'all', 'data-turbolinks-track': 'reload' %>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet" />
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>
</head>

<body>
<%= render 'layouts/topnav' %>
<br />
<div class="container-fluid">
  <div class="row">
    <div class="col-2">
      <%= render 'layouts/sidenav' %>
    </div>
    <div class="col-10">
      <%= yield %>
    </div>
  </div>
</div>


</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Workouts</title>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
</head>

<body>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/members/_form.html.erb
<%= form_with(model: member, local: true) do |form| %>
  <% if member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row form-group">
    <div class="col-sm">
      <%= form.label :first_name %>
      <%= form.text_field :first_name, class: "form-control" %>
    </div>

    <div class="col-sm">
      <%= form.label :last_name %>
      <%= form.text_field :last_name, class: "form-control" %>
    </div>

    <div class="col-sm">
      <%= form.label :height %>
      <%= form.number_field :height, class: "form-control" %>
    </div>
  </div>

  <br />

  <div class="actions">
    <%= form.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/members/edit.html.erb
<h1>Editing Member</h1>

<%= render 'form', member: @member %>

app/views/members/index.html.erb
<% if notice %>
  <div class="alert alert-success" role="alert">
    <%= notice %>
  </div>
<% end %>

<h1>Members</h1>
<%= render "layouts/search" %>
<table class="table">
  <thead>
    <tr>
      <th>Last name</th>
      <th>First name</th>
      <th>Height</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= member.last_name %></td>
        <td><%= member.first_name %></td>
        <td><%= member.height %></td>
<!--        <td><%##= link_to 'Show', member %></td>-->
        <td><%= link_to 'Edit', edit_member_path(member) %></td>
        <td><%= link_to 'Destroy', member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Member', new_member_path, class: "btn btn-primary" %>

app/views/members/new.html.erb
<h1>New Member</h1>

<%= render 'form', member: @member %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @member.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @member.last_name %>
</p>

<p>
  <strong>Height:</strong>
  <%= @member.height %>
</p>

<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', members_path %>

app/views/workouts/_form.html.erb
<%= form_with(model: workout, local: true) do |form| %>
  <% if workout.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(workout.errors.count, "error") %> prohibited this workout from being saved:</h2>

      <ul>
      <% workout.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :workout_date %>
    <%= form.datetime_select :workout_date, class: "form-control" %>
  </div>

  <div class="row form-group">
    <div class="col-sm">
      <%= form.label :weight %>
      <%= form.text_field :weight, class: "form-control" %>
    </div>
    <div class="col-sm">
      <%= form.label :bone_density %>
      <%= form.text_field :bone_density, class: "form-control" %>
    </div>
    <div class="col-sm">
      <%= form.label :bmi %>
      <%= form.text_field :bmi, class: "form-control" %>
    </div>
    <div class="col-sm">
      <%= form.label :body_fat %>
      <%= form.text_field :body_fat, class: "form-control" %>
    </div>
    <div class="col-sm">
      <%= form.label :muscle_mass %>
      <%= form.text_field :muscle_mass, class: "form-control" %>
    </div>
    <div class="col-sm">
      <%= form.label :water %>
      <%= form.text_field :water, class: "form-control" %>
    </div>
  </div>

  <div class="row form-group">
    <div class="col-sm">
      <%= form.label :member_id %><br />
      <%= form.collection_select(:member_id, Member.order(:last_name) , :id, :last_name, { prompt: true }, class: "autocomplete") %>
    </div>
  </div>

  <div class="row form-group">
    <div class="col-sm">
      <%= form.label :comments %>
      <%= form.text_area :comments, class: "form-control" %>
    </div>
  </div>

  <h3>Exercise</h3>
  <%= form.nested_fields_for :exercises do |ff| %>
    <br />
    <div class="card" style="margin: 10px 0; padding: 20px; background-color: #eee">
      <%= ff.remove_nested_fields_link 'Remove me', class: 'btn btn-danger', role: 'button' %>

      <br />
      <div class="row">
        <div class="col-sm">
          <%= ff.label :name %>
          <%= ff.text_field :name, class: "form-control" %>
        </div>

        <div class="col-sm">
          <%= ff.label :total_set %>
          <%= ff.number_field :total_set, class: "form-control" %>
        </div>

        <div class="col-sm">
          <%= ff.label :weights %>
          <%= ff.number_field :weights, class: "form-control" %>
        </div>

        <div class="col-sm">
          <%= ff.label :duration %>
          <%= ff.number_field :duration, class: "form-control" %>
        </div>
      </div>
      <div class="row">
        <div class="col-sm">
          <%= ff.label :comments %>
          <%= ff.text_area :comments, class: "form-control" %>
        </div>
      </div>
      <%= ff.hidden_field :_destroy, class: 'btn btn-danger' %>
    </div>
  <% end %>
  <%= form.add_nested_fields_link :exercises, 'Add exercise', class: "btn btn-secondary" %>

  <br />
  <br />
  <br />

  <div class="actions">
    <%= form.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/workouts/edit.html.erb
<h1>Editing Workout</h1>

<%= render 'form', workout: @workout %>

app/views/workouts/index.html.erb
<% if notice %>
  <div class="alert alert-success" role="alert">
    <%= notice %>
  </div>
<% end %>

<h1>Workouts</h1>
<%= render "layouts/search" %>
<table class="table">
  <thead>
    <tr>
      <th>Workout date</th>
      <th>Comments</th>
      <th>Weight</th>
      <th>Bone density</th>
      <th>Bmi</th>
      <th>Body fat</th>
      <th>Muscle mass</th>
      <th>Water</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @workouts.each do |workout| %>
      <tr>
        <td><%= workout.workout_date %></td>
        <td><%= workout.comments %></td>
        <td><%= workout.weight %></td>
        <td><%= workout.bone_density %></td>
        <td><%= workout.bmi %></td>
        <td><%= workout.body_fat %></td>
        <td><%= workout.muscle_mass %></td>
        <td><%= workout.water %></td>
        <td><%= link_to 'Show', workout %></td>
        <td><%= link_to 'Edit', edit_workout_path(workout) %></td>
        <td><%= link_to 'Destroy', workout, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Workout', new_workout_path, class: "btn btn-primary" %>

app/views/workouts/new.html.erb
<h1>New Workout</h1>

<%= render 'form', workout: @workout %>

app/views/workouts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Workout date:</strong>
  <%= @workout.workout_date %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @workout.comments %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @workout.weight %>
</p>

<p>
  <strong>Bone density:</strong>
  <%= @workout.bone_density %>
</p>

<p>
  <strong>Bmi:</strong>
  <%= @workout.bmi %>
</p>

<p>
  <strong>Body fat:</strong>
  <%= @workout.body_fat %>
</p>

<p>
  <strong>Muscle mass:</strong>
  <%= @workout.muscle_mass %>
</p>

<p>
  <strong>Water:</strong>
  <%= @workout.water %>
</p>

<%= link_to 'Edit', edit_workout_path(@workout) %> |
<%= link_to 'Back', workouts_path %>